# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQ17AKOplkzO4fOathJovw81yfzSZBca
"""

import streamlit as st
import pdfplumber
import pandas as pd
import io

st.set_page_config(page_title="Invoice Extractor", layout="centered")

st.title("📄 Invoice Extractor")
st.write("Upload your invoice PDF and download extracted Excel data.")

uploaded_file = st.file_uploader("Upload Invoice PDF", type=["pdf"])

if uploaded_file is not None:

    with pdfplumber.open(uploaded_file) as pdf:
        text = ""
        for page in pdf.pages:
            text += page.extract_text()

    # === YOUR EXTRACTION LOGIC HERE ===
    # Example placeholder
    invoice_number = "12345"
    invoice_date = "2025-01-01"

    data = {
        "Invoice Number": [invoice_number],
        "Invoice Date": [invoice_date],
    }

    df = pd.DataFrame(data)

    st.success("Extraction complete!")

    st.dataframe(df)

    # Convert to Excel in memory
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False)

    st.download_button(
        label="📥 Download Excel",
        data=output.getvalue(),
        file_name="invoice_result.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )