# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQ17AKOplkzO4fOathJovw81yfzSZBca
"""

import streamlit as st
import pdfplumber
import pandas as pd
import re
import io

st.set_page_config(page_title="Invoice Extractor", layout="centered")

st.title("📄 Invoice Extractor")
st.write("Upload one or multiple invoice PDFs and download extracted data.")

uploaded_files = st.file_uploader(
    "Upload Invoice PDFs",
    type=["pdf"],
    accept_multiple_files=True
)

if uploaded_files:

    all_data = []

    for uploaded_file in uploaded_files:

        invoice_number = uploaded_file.name.replace(".pdf", "")
        rows = []

        with pdfplumber.open(uploaded_file) as pdf:
            for page in pdf.pages:
                text = page.extract_text()
                if not text:
                    continue

                lines = text.split("\n")

                for line in lines:
                    match = re.search(
                        r'(.+?)\s+(\d+)\s+([A-Za-z]+)\s+([\d.]+)\s+([\d,]+\.\d+)$',
                        line
                    )

                    if match:
                        description = match.group(1).strip()
                        quantity = match.group(2)
                        unit = match.group(3)
                        unit_price = match.group(4)
                        amount = match.group(5)

                        rows.append([
                            invoice_number,
                            description,
                            quantity,
                            unit,
                            unit_price,
                            amount
                        ])

        if rows:
            df_invoice = pd.DataFrame(
                rows,
                columns=[
                    "Invoice",
                    "Description",
                    "Quantity",
                    "Unit",
                    "Unit Price",
                    "Amount"
                ]
            )

            all_data.append(df_invoice)

    if all_data:
        final_df = pd.concat(all_data, ignore_index=True)

        st.success("✅ Extraction complete!")
        st.dataframe(final_df)

        # Download as Excel
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            final_df.to_excel(writer, index=False)

        st.download_button(
            label="📥 Download Excel",
            data=output.getvalue(),
            file_name="invoice_result.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
    else:
        st.warning("⚠ No table data detected.")